server:
  port: 8080
spring:
  application:
    name: department-service

  datasource:
    url: jdbc:mysql://localhost:3306/department_demo_1?createDatabaseIfNotExist=true
    username: root
    password: th15@rud@51th
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


logging:
  level:
    org.hibernate.SQL: DEBUG


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
