server:
  port: 8081
spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:mysql://localhost:3306/employee_demo_2?createDatabaseIfNotExist=true
    username: root
    password: th15@rud@51th
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
